name: CI
on:
  push:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
  #environment
env:
  MONGO_DB_URL: ${{secrets.MONGO_DB_URL}}
  NIDA_API_KEY: ${{secrets.NIDA_API_KEY}}
  EMAIL_FROM: ${{secrets.EMAIL_FROM}}
  EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ["4.4"]

    concurrency: test_environment
    env:
      MONGO_DB_URL: ${{secrets.MONGO_DB_URL}}
      NIDA_API_KEY: ${{secrets.NIDA_API_KEY}}
      EMAIL_FROM: ${{secrets.EMAIL_FROM}}
      EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 12345
      - name: install global dependecies
        run: npm install

      - name: Install all dependecies api-gateway
        working-directory: ./bbis-api-gateway
        run: npm install

      - name: Install all dependecies microservices/access-donor
        working-directory: ./bbis-microservices/access-donor
        run: npm install

      - name: Run the tests
        working-directory: ./bbis-microservices/access-donor
        run: npm run test
        env:
          CI: true
